[package]
name = "second"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
quick-xml = { version = "0.23", features = [ "serialize" ] }